# Generated by Django 5.2.4 on 2025-08-20 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto')], default='carro', max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('categoria', models.CharField(choices=[('passeio', 'Passeio'), ('utilitario', 'Utilitário')], default='passeio', max_length=10)),
                ('km_por_l', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
