# Generated by Django 5.2.4 on 2025-08-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_veiculo', '0001_initial'),
    ]

    operations = [
        # Esta migração adiciona validações personalizadas via código Python
        # As validações são implementadas no serializer e no método clean() do modelo
    ]
