# Generated by Django 5.2.4 on 2025-08-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(choices=[('passeio', 'Passeio'), ('utilitario', 'Utilitário')], default='passeio', max_length=10),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='km_por_l',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto')], default='carro', max_length=10),
        ),
    ]
