# Generated by Django 5.2.3 on 2025-08-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_veiculo', '0002_veiculo_categoria_veiculo_km_por_l_veiculo_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
