# Generated by Django 5.2.4 on 2025-08-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('quilometragem', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('localizacao', models.CharField(max_length=100)),
                ('link_externo', models.URLField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='anuncios_fotos/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
