# Generated by Django 5.2.5 on 2025-09-10 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0002_anuncioveiculo_postagem_delete_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncioveiculo',
            options={'ordering': ['-data_publicacao']},
        ),
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AddField(
            model_name='anuncioveiculo',
            name='data_moderacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anuncioveiculo',
            name='is_visivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anuncioveiculo',
            name='moderado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios_moderados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anuncioveiculo',
            name='motivo_moderacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anuncioveiculo',
            name='status',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('pendente', 'Pendente'), ('rejeitado', 'Rejeitado'), ('removido', 'Removido')], default='aprovado', max_length=20),
        ),
        migrations.AddField(
            model_name='postagem',
            name='data_moderacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postagem',
            name='is_visivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postagem',
            name='moderado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postagens_moderadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postagem',
            name='motivo_moderacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postagem',
            name='status',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('pendente', 'Pendente'), ('rejeitado', 'Rejeitado'), ('removido', 'Removido')], default='aprovado', max_length=20),
        ),
    ]
