# Generated by Django 5.2.4 on 2025-08-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_entregadespesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEntregaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rendimento', models.CharField(choices=[('unitario', 'Valor Unitário por Pacote'), ('diaria', 'Valor por Diária')], max_length=10)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_pacotes', models.PositiveIntegerField()),
                ('pacotes_entregues', models.PositiveIntegerField()),
                ('pacotes_nao_entregues', models.PositiveIntegerField()),
                ('categoria_despesa', models.CharField(choices=[('alimentacao', 'Alimentação'), ('automotivo', 'Gasto Automotivo'), ('pedagio', 'Pedágio'), ('seguro', 'Seguro Mensal'), ('outros', 'Outros')], max_length=20)),
                ('valor_despesa', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descricao_outros', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.DeleteModel(
            name='RegistroEntrega',
        ),
    ]
