# Generated by Django 5.2.4 on 2025-08-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_entregadespesa', '0002_registroentregadespesa_delete_despesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroentregadespesa',
            name='categoria_despesa',
            field=models.CharField(choices=[('nenhuma', 'Nenhuma Despesa'), ('alimentacao', 'Alimentação'), ('automotivo', 'Gasto Automotivo'), ('pedagio', 'Pedágio'), ('seguro', 'Seguro Mensal'), ('outros', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registroentregadespesa',
            name='valor_despesa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
