# Generated by Django 5.2.3 on 2025-08-12 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_entregadespesa', '0003_alter_registroentregadespesa_categoria_despesa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_despesa', models.CharField(choices=[('alimentacao', 'Alimentação'), ('combustivel', 'Combustível'), ('manutencao', 'Manutenção do Veículo'), ('pedagio', 'Pedágio'), ('estacionamento', 'Estacionamento'), ('seguro', 'Seguro'), ('licenciamento', 'Licenciamento'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('quantidade_entregues', models.PositiveIntegerField()),
                ('quantidade_nao_entregues', models.PositiveIntegerField()),
                ('tipo_pagamento', models.CharField(choices=[('unitario', 'Valor Unitário por Pacote'), ('diaria', 'Valor por Diária'), ('por_hora', 'Valor por Hora'), ('fixo', 'Valor Fixo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-hora_inicio'],
            },
        ),
    ]
