# Generated by Django 5.2.5 on 2025-09-24 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_entregadespesa', '0004_despesa_registrotrabalho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('nome', 'entregador')},
            },
        ),
        migrations.AddField(
            model_name='despesa',
            name='categoria_personalizada',
            field=models.ForeignKey(blank=True, help_text='Categoria personalizada criada pelo usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_entregadespesa.categoriadespesa'),
        ),
    ]
