# Generated by Django 5.2.3 on 2025-10-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_entregadespesa', '0005_categoriadespesa_despesa_categoria_personalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='tipo_despesa',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('combustivel', 'Combustível'), ('manutencao', 'Manutenção do Veículo'), ('pedagio', 'Pedágio'), ('estacionamento', 'Estacionamento'), ('seguro', 'Seguro'), ('licenciamento', 'Licenciamento'), ('ferramentas', 'Ferramentas e Equipamentos'), ('comunicacao', 'Comunicação (Celular/Internet)'), ('uniforme', 'Uniforme e EPIs'), ('documentacao', 'Documentação e Licenças'), ('outros', 'Outros')], max_length=20),
        ),
    ]
