# Generated by Django 5.2.3 on 2025-10-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_entregadespesa', '0006_alter_despesa_tipo_despesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadespesa',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
