# Generated by Django 5.2.3 on 2025-06-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_entregador_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
