# Generated by Django 5.2.3 on 2025-08-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_entregador_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregador',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
