# Generated by Django 5.2.3 on 2025-08-26 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_entregador_cep_entregador_cidade_entregador_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregador',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
