# Generated by Django 5.2.3 on 2025-08-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_entregador_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]

