# Generated by Django 5.2.5 on 2025-09-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_entregador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregador',
            name='email_codigo_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='email_codigo_validacao',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='email_validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entregador',
            name='telefone_codigo_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='telefone_codigo_validacao',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='telefone_validado',
            field=models.BooleanField(default=False),
        ),
    ]
