# Generated by Django 5.2.5 on 2025-09-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_entregador_email_codigo_expira_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregador',
            name='email_codigo_expira_em',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='email_codigo_validacao',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='email_validado',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='telefone_codigo_expira_em',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='telefone_codigo_validacao',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='telefone_validado',
        ),
    ]
