# Generated by Django 5.2.5 on 2025-09-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_entregador_email_codigo_expira_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregador',
            name='email_codigo_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='email_codigo_validacao',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='email_validado',
            field=models.BooleanField(default=False),
        ),
    ]
