# Generated by Django 5.2.3 on 2025-10-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_entregador_email_codigo_expira_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregador',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
