# Generated by Django 5.2.3 on 2025-10-10 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_entregador_two_factor_backup_codes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregador',
            name='two_factor_backup_codes',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='two_factor_secret',
        ),
        migrations.AddField(
            model_name='entregador',
            name='last_2fa_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='two_factor_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twofactorverification',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('setup', 'Setup'), ('disable', 'Disable')], default='login', max_length=20),
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web'), ('tablet', 'Tablet')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used'],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
