# Generated by Django 5.2.3 on 2025-10-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_entregador_two_factor_backup_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregador',
            name='registration_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='registration_code_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entregador',
            name='registration_code_blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='registration_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='registration_verified',
            field=models.BooleanField(default=False),
        ),
    ]
